api:
    entities:
        Oro\Bundle\ProductBundle\Entity\ProductUnitPrecision:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product-unit-precision.md'

        Oro\Bundle\ProductBundle\Entity\ProductUnit:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_unit.md'
            fields:
                label:
                    data_type: string
                    property_path: _
                shortLabel:
                    data_type: string
                    property_path: _
                pluralLabel:
                    data_type: string
                    property_path: _
                shortPluralLabel:
                    data_type: string
                    property_path: _

        Oro\Bundle\ProductBundle\Entity\ProductImage:
            documentation_resource: '@OroProductBundle/Resources/doc/api_frontend/product_image.md'
            fields:
                mimeType:
                    data_type: string
                    property_path: image.mimeType
                types:
                    data_type: array
                    property_path: _
                    depends_on: [ types.type ]
                # declare excluded field for "types" entity property
                # to be able to use "types" property in "depends_on" option
                _types:
                    property_path: types
                    exclude: true
                    max_results: -1
                files:
                    data_type: array
                    property_path: _
                    depends_on: [ types.type, image.id, image.filename ]
            filters:
                fields:
                    types:
                        data_type: string
                        allow_array: true
                        property_path: types.type
                        collection: true
                        operators: [ '=', '!=', '*', '!*', '~', '!~' ]
            actions:
                create: true
                update: true
                delete: true
                delete_list: true
                
        Oro\Bundle\ProductBundle\Entity\ProductImageType:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product_image_type.md'

        Oro\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@OroProductBundle/Resources/doc/api_frontend/product.md'
            fields:
                denormalizedDefaultName:
                    exclude: true
                denormalizedDefaultNameUppercase:
                    exclude: true
                skuUppercase:
                    exclude: true
                status:
                    exclude: true

                name:
                    data_type: localizedFallbackValue:names
                shortDescription:
                    data_type: localizedFallbackValue:shortDescriptions
                description:
                    data_type: localizedFallbackValue:descriptions
                productType:
                    property_path: type
                productFamily:
                    property_path: attributeFamily
                productAttributes:
                    data_type: object
                    property_path: _
                    depends_on: [ type, attributeFamily.id ]

                variantAttributeNames:
                    property_path: variantFields
                variantProducts:
                    target_class: Oro\Bundle\ProductBundle\Entity\Product
                    target_type: to-many
                    property_path: _
                    max_results: -1
                parentProducts:
                    target_class: Oro\Bundle\ProductBundle\Entity\Product
                    target_type: to-many
                    property_path: _
                    max_results: -1
                unitPrecisions:
                    data_type: array
                    property_path: _
                    depends_on:
                        - unitPrecisions.id
                        - unitPrecisions.unit.code
                        - unitPrecisions.precision
                        - unitPrecisions.conversionRate
                        - unitPrecisions.sell
                        - primaryUnitPrecision.id
                # declare excluded field for "unitPrecisions" entity property
                # to be able to use "unitPrecisions" property in "depends_on" option
                _unitPrecisions:
                    property_path: unitPrecisions
                    exclude: true
                    max_results: -1
                url:
                    data_type: string
                    property_path: _
                urls:
                    data_type: array
                    property_path: _
                inventoryStatus:
                    property_path: inventory_status
                
            filters:
                fields:
                    sku:
                        allow_array: true
                    inventoryStatus:
                        allow_array: true
                    variants: # processed by Oro\Bundle\ProductBundle\Api\Processor\HandleVariantsFilter
                        data_type: boolean
                        operators: [ '=' ]
                        property_path: _
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
            subresources:
                variantProducts:
                    actions:
                        get_subresource:
                            page_size: -1 # disable paging
                        get_relationship:
                            page_size: -1 # disable paging
                parentProducts:
                    actions:
                        get_subresource:
                            page_size: -1 # disable paging
                        get_relationship:
                            page_size: -1 # disable paging
        Extend\Entity\EV_Prod_Inventory_Status:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product.md'

        Oro\Bundle\ProductBundle\Entity\RelatedItem\RelatedProduct:
            documentation_resource: '@OroProductBundle/Resources/doc/api/related_product.md'
            actions:
                get:
                    description: 'Get Related Product Relationship'
                delete:
                    description: 'Delete Related Product Relationship'
                get_list:
                    description: 'Get Related Product Relationships'
                delete_list:
                    description: 'Delete Related Product Relationships'
                create:
                    description: 'Create Related Product Relationships'
                    fields:
                        product:
                            form_options:
                                constraints:
                                    - NotBlank: ~
                        relatedItem:
                            form_options:
                                constraints:
                                    - NotBlank: ~
                update: false

        Oro\Bundle\ProductBundle\Entity\Brand:
            documentation_resource: '@OroProductBundle/Resources/doc/api/brand.md'
            fields:
                defaultTitle:
                    exclude: true

        Oro\Bundle\ProductBundle\Entity\ProductVariantLink:
            documentation_resource: '@OroProductBundle/Resources/doc/api/product-variant-links.md'

        Oro\Bundle\AttachmentBundle\Entity\File:
            documentation_resource: '@OroProductBundle/Resources/doc/api/file.md'
            fields:
                filePath:
                    data_type: array
                    depends_on: [filename,mimeType,originalFilename,extension,parentEntityClass]
                    form_options:
                        mapped: false
