api:
    entities:
        Oro\Bundle\OrderBundle\Entity\Order:
            documentation_resource: '@OroTaxBundle/Resources/doc/api_frontend/order.md'
            fields:
                totalIncludingTax:
                    data_type: money
                    property_path: _
                totalExcludingTax:
                    data_type: money
                    property_path: _
                totalTaxAmount:
                    data_type: money
                    property_path: _

        Oro\Bundle\TaxBundle\Entity\ProductTaxCode:
            documentation_resource: '@OroTaxBundle/Resources/doc/api/product_tax_code.md'
            fields:
                taxCode:
                    description: Tax code
                    data_type: association:manyToOne
                organization:
                    exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
            subresources:
                organization:
                    actions:
                        update_relationship: false
